trigger:
- dev

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  displayName: 'Copy Terraform files to artifacts'
  inputs:
    SourceFolder: azure_infrastructure/terraform
    TargetFolder: '$(build.artifactstagingdirectory)/terraform'
   
- task: CopyFiles@2
  displayName: 'Copy SQL schema script'
  inputs:
    SourceFolder: 'azure_infrastructure/'
    Contents: 'dbschema.sql'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
