trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  displayName: 'Copy Terraform files to artifacts'
  inputs:
    SourceFolder: azure_infrastructure/terraform
    TargetFolder: '$(build.artifactstagingdirectory)/terraform'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'